# Generated by Django 5.1.6 on 2025-03-05 10:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='qccfuwidka0xmyyer58i', max_length=255, verbose_name='image'),
        ),
    ]
